# ===================================================================
# Artemis specific properties
# ===================================================================

artemis:
    repo-clone-path: ./repos/
    repo-download-clone-path: ./repos-download/
    encryption-password: kjashkdhwquhajjhdkaj     # arbitrary password for encrypting database values
    user-management:
        use-external: false
        external:
            url: https://jira.ase.in.tum.de
            user: <username>        # e.g. ga12abc
            password: <password>
            admin-group-name: tumuser
        ldap:                       # the whole section is optional: whether user details (such as the registration number) can be obtained from a LDAP service
            url: <url>
            user-dn: <user-dn>
            password: <password>
            base: <base>
            allowed-username-pattern: '^([a-z]{2}\d{2}[a-z]{3})'    # example for a TUM identifier, e.g. ab12cde
        internal-admin:
            username: artemis_admin
            password: GJsduaoj57289gst
        registration:
            enabled: true
            allowed-email-pattern: '[a-zA-Z0-9_\-\.\+]+@(uni-bonn\.de)'
            allowed-email-pattern-readable: '@uni-bonn.de'
        course-registration: # the whole section is optional: whether there is a restriction for the self-registration of students in courses
            allowed-username-pattern: '.*'    # example for a TUM identifier, e.g. ab12cde
        login:
            account-name: Artemis                   # optional: customization for the welcome page "please sign in with your <account-name> account"
    version-control:
        url: https://gitlab.christiantiefenau.de
        user: artemis    # e.g. ga12abc
        password: NEefWQCNqJKforP93bLGDYXvfd5oaDen4
        token: TBqc9L-k4JV8odyUYkqB                 # VCS API token giving Artemis full Admin access. Not needed for Bamboo+Bitbucket
        ci-token: 8cf20eafee74e11a0f3a4889357c228f   # Token generated by the CI (e.g. Jenkins) for webhooks from the VCS to the CI. Not needed for Bamboo+Bitbucket
        ssh-template-clone-url: ssh://git@bitbucket.ase.in.tum.de:7999/    # Url Stem for cloning via ssh, for gitlab use 'ssh://git@artemistest2gitlab.ase.in.tum.de:2222/'
        ssh-keys-url-path: /plugins/servlet/ssh/account/keys  # Url Path to access a users ssh keys, for gitlab this is '/profile/keys'
    continuous-integration:
        user: artemis    # e.g. ga12abc
        password: NEefWQCNqJKforP93bLGDYXvfd5oaDen4
        token: <token>
        url: https://jenkins.christiantiefenau.de
        vcs-application-link-name: LS1 Bitbucket Server     # If the VCS and CI are directly linked (normally only for Bitbucket + Bamboo)
        empty-commit-necessary: true                        # Do we need an empty commit for new exercises/repositories in order for the CI to register the repo
        # Hash/key of the ci-token, equivalent e.g. to the ci-token in version-control
        # Some CI systems, like Jenkins, offer a specific token that gets checked against any incoming notifications
        # from a VCS trying to trigger a build plan. Only if the notification request contains the correct token, the plan
        # is triggered. This can be seen as an alternative to sending an authenticated request to a REST API and then
        # triggering the plan.
        # In the case of Artemis, this is only really needed for the Jenkins + GitLab setup, since the GitLab plugin in
        # Jenkins only allows triggering the Jenkins jobs using such a token. Furthermore, in this case, the value of the
        # hudson.util.Secret is stored in the build plan, so you also have to specify this encrypted string here and NOT the actual token value itself!
        # You can get this by GETting any job.xml for a job with an activated GitLab step and your token value of choice.
        secret-push-token: AQAAABAAAAAwhvfqQprsnv07X74r7jdgYb4TyUH7m4uDg15jkzmtgJWyXUwj3s4jTTfs87OdXmVk9oeKWwIh807igqZqn67LDQ==
        # Key of the saved credentials for the VCS service
        # Bamboo: not needed
        # Jenkins: You have to specify the key from the credentials page in Jenkins under which the user and
        #          password for the VCS are stored
        vcs-credentials: 70fd2abc-80e8-4382-b225-448c845a2326
        # Key of the credentials for the Artemis notification token
        # Bamboo: not needed
        # Jenkins: You have to specify the key from the credentials page in Jenkins under which the authentication-token is stored
        artemis-authentication-token-key: bb3f22ea-c6a1-4e73-b910-816b828f6853
        # The actual value of the notification token to check against in Artemis. This is the token that gets send with
        # every request the CI system makes to Artemis containing a new result after a build.
        # Bamboo: The token value you use for the Server Notification Plugin
        # Jenkins: The token value you use for the Server Notification Plugin and is stored under the notification-token credential above
        artemis-authentication-token-value: joidsjfljwuei98jH
    lti: # only important for online courses that use LTI, can typically be ignored
        id: artemis_lti
        oauth-key: artemis_lti_key
        oauth-secret: <secret>
        user-prefix-edx: edx_
        user-prefix-u4i: u4i_
        user-group-name-edx: edx
        user-group-name-u4i: u4i
    git:
        name: Artemis
        email: artemis@in.tum.de
    automatic-text:
        segmentation-url: http://localhost:8000/segment
        embedding-url: http://localhost:8001/embed
        embedding-chunk-size: 50
        clustering-url: http://localhost:8002/cluster
        feedback-consistency-url: http://localhost:8001/feedback_consistency
        secret: null
    athene:
        base64-secret: YWVuaXF1YWRpNWNlaXJpNmFlbTZkb283dXphaVF1b29oM3J1MWNoYWlyNHRoZWUzb2huZ2FpM211bGVlM0VpcAo=
        token-validity-in-seconds: 10800
spring:
    mail:
        host: christiantiefenau.de
        port: 587
        username: lehre@christiantiefenau.de
        password: fruf9yass6FANK!wil
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls:
                enable: true
            ssl:
                trust: christiantiefenau.de
jhipster:
    mail:
        base-url: https://alpro.besec.uni-bonn.de
        from: lehre@christiantiefenau.de
