version: "2"
networks:
    artemis:
        driver: "bridge"
        ipam:
            driver: default
            config:
                -   subnet: 172.20.24.0/24

services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        env_file:
            -   config/gilab/gitlab.env
        volumes:
            - artemis-gitlab-data:/var/opt/gitlab
            - artemis-gitlab-logs:/var/log/gitlab
            - artemis-gitlab-config:/etc/gitlab
        mem_limit: 3000m
        hostname: gitlab
        networks:
            artemis:
                ipv4_address: 172.20.24.3
    jenkins:
        build: ../jenkins
        env_file:
            -   config/jenkins/jenkins.env
        volumes:
            - artemis-jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
        hostname: jenkins
        networks:
            artemis:
                ipv4_address: 172.20.24.4


volumes:
    artemis-gitlab-data:
    artemis-gitlab-logs:
    artemis-gitlab-config:
    artemis-jenkins-data:
